# AUTOGENERATED! DO NOT EDIT! File to edit: 02_core.caseload.ipynb (unless otherwise specified).

__all__ = ['CESSATION_CONTINUATION', 'get_generated_caseload_data_bymonth']

# Cell
import pandas as pd
import numpy  as np
from datetime import datetime
import altair as alt

#from cheeky_monkey import *

pd.set_option('display.max_columns', 30) # set so can see all columns of the DataFrame

from vega_datasets import data
_=alt.data_transformers.disable_max_rows()


CESSATION_CONTINUATION = {
    'Driver Deceased': 'Deceased',
    'Drivers found medically unfit to drive':'Cessation',
    'Drivers that did not respond; cancelled license':'Cessation',
    'Drivers that voluntarily surrendered their license':'Cessation',
    'Drivers ultimately found fit to drive':'Continuation',
    'Cases remaining open at time of reporting':'Continuation'
}



# Cell
def get_generated_caseload_data_bymonth(f_path):
    filepath = f_path + 'caseloaddata_by_month.csv'
    caseload_data_by_month = pd.read_csv(filepath,parse_dates=['CASE_OPENED_DT'])
    caseload_data_by_month['Opened Month'] = caseload_data_by_month.apply(lambda x: x['CASE_OPENED_DT'].strftime('%b') + '-' + x['CASE_OPENED_DT'].strftime('%Y'), axis=1)
    return caseload_data_by_month