# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"derive_statuscount_percase": "00_core.ipynb",
         "example_exports_func": "00_core.ipynb",
         "imgs_save": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ezrider.github.io/cheeky_monkey/"

git_url = "https://github.com/ezrider/cheeky_monkey/tree/{branch}/"

def custom_doc_links(name): return None
