# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"from_dob_to_age": "00_core.ipynb",
         "derive_statuscount_percase": "01_core.baseline.ipynb",
         "imgs_save": "01_core.baseline.ipynb",
         "ORIGIN_MAPPINGS": "01_core.baseline.ipynb",
         "get_fte_days_2018": "01_core.baseline.ipynb",
         "example_exports_func": "01_core.baseline.ipynb",
         "get_statuses": "01_core.baseline.ipynb",
         "get_processed_case_data": "01_core.baseline.ipynb",
         "get_2018processed_case_data": "01_core.baseline.ipynb",
         "CESSATION_CONTINUATION": "02_core.caseload.ipynb",
         "get_generated_caseload_data_bymonth": "02_core.caseload.ipynb",
         "data_file_path": "10. Cost Analysis Baseline - 2018 Over 80 Cases by Case Origin.ipynb",
         "cases2018_df": "10. Cost Analysis Baseline - 2018 Over 80 Cases by Case Origin.ipynb"}

modules = ["core.py",
           "core/baseline.py",
           "core/caseload.py",
           "None.py"]

doc_url = "https://ezrider.github.io/cheeky_monkey/"

git_url = "https://github.com/ezrider/cheeky_monkey/tree/{branch}/"

def custom_doc_links(name): return None
